'use strict';
/* ============================================================================
   LOCAL WINDOWS TTS (SAPI) — added 2026-07-28
   ----------------------------------------------------------------------------
   WHY THIS EXISTS
   edge-tts.js talks to an UNOFFICIAL Microsoft endpoint. It worked for weeks,
   then Microsoft added a Sec-MS-GEC token requirement and every call started
   returning 403 mid-session — read-aloud died with no warning. Even with the
   token implemented, that endpoint can change again without notice, and Anoop
   trades on this app: he explicitly asked for something that will not break
   during trading hours.

   This module removes the network from the equation entirely. It drives the
   speech engine built into Windows (System.Speech / SAPI) via PowerShell:
     - fully offline, no API key, no token, no rate limit
     - cannot be revoked or changed by a third party
     - uses whatever voices are installed on the machine

   Voice quality is below Edge's neural voices, which is why this is tier 2:
   Edge TTS first (best voice), this second (always works), browser
   speechSynthesis last (client-side backstop). See handleTtsSpeak in server.js.

   Indian English: Windows ships "Microsoft Heera" (en-IN female) on many
   installs; we prefer it, then any en-IN voice, then any female voice, then
   the system default. If none of the preferred ones exist the default still
   speaks — it just won't be Indian-accented.
   ========================================================================== */

const { execFile } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');

const IS_WINDOWS = process.platform === 'win32';

// Preference order for picking a voice. Matched case-insensitively as a
// substring against each installed voice's name.
const VOICE_PREFERENCES = ['Heera', 'en-IN', 'India', 'Zira', 'Female'];

function isAvailable() {
  return IS_WINDOWS;
}

/**
 * Synthesize `text` to a WAV buffer using the local Windows speech engine.
 *
 * Text is passed via a UTF-8 temp FILE rather than interpolated into the
 * PowerShell command line. That matters: chat messages contain quotes,
 * dollar signs, backticks and newlines, all of which are PowerShell
 * metacharacters — inlining them would corrupt the script or, worse, execute
 * part of the message. Reading from a file sidesteps quoting entirely.
 *
 * @param {string} text
 * @returns {Promise<Buffer>} WAV audio
 */
function synthesizeToWav(text) {
  return new Promise((resolve, reject) => {
    if (!IS_WINDOWS) return reject(new Error('Local TTS requires Windows (System.Speech).'));
    const clean = String(text || '').trim();
    if (!clean) return reject(new Error('Nothing to speak.'));

    const id = crypto.randomBytes(8).toString('hex');
    const tmpDir = os.tmpdir();
    const txtPath = path.join(tmpDir, 'copilot-tts-' + id + '.txt');
    const wavPath = path.join(tmpDir, 'copilot-tts-' + id + '.wav');

    const cleanup = () => {
      for (const p of [txtPath, wavPath]) {
        try { if (fs.existsSync(p)) fs.unlinkSync(p); } catch (e) { /* temp file, ignore */ }
      }
    };

    try {
      fs.writeFileSync(txtPath, clean, 'utf8');
    } catch (e) {
      return reject(new Error('Local TTS: could not write temp text file — ' + e.message));
    }

    // Single-quoted PowerShell strings only need '' escaping, and these paths
    // are generated by us (hex id in the OS temp dir), so they're safe.
    const psScript = `
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Speech
$text = [System.IO.File]::ReadAllText('${txtPath.replace(/'/g, "''")}', [System.Text.Encoding]::UTF8)
$synth = New-Object System.Speech.Synthesis.SpeechSynthesizer
$prefs = @(${VOICE_PREFERENCES.map(v => "'" + v + "'").join(',')})
$installed = $synth.GetInstalledVoices() | Where-Object { $_.Enabled } | ForEach-Object { $_.VoiceInfo.Name }
$chosen = $null
foreach ($p in $prefs) {
  foreach ($n in $installed) {
    if ($n -like ('*' + $p + '*')) { $chosen = $n; break }
  }
  if ($chosen) { break }
}
if ($chosen) { try { $synth.SelectVoice($chosen) } catch { } }
$synth.Rate = 0
$synth.SetOutputToWaveFile('${wavPath.replace(/'/g, "''")}')
$synth.Speak($text)
$synth.Dispose()
Write-Output $chosen
`.trim();

    execFile(
      'powershell.exe',
      ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-Command', psScript],
      { timeout: 60000, windowsHide: true, maxBuffer: 1024 * 1024 },
      (err, stdout, stderr) => {
        if (err) {
          cleanup();
          return reject(new Error('Local TTS failed: ' + (stderr || err.message || '').toString().trim().slice(0, 300)));
        }
        try {
          if (!fs.existsSync(wavPath)) {
            cleanup();
            return reject(new Error('Local TTS produced no audio file.'));
          }
          const buf = fs.readFileSync(wavPath);
          cleanup();
          if (!buf.length) return reject(new Error('Local TTS produced an empty audio file.'));
          const usedVoice = String(stdout || '').trim();
          if (usedVoice) console.log('[local-tts] voice:', usedVoice);
          resolve(buf);
        } catch (e) {
          cleanup();
          reject(new Error('Local TTS: could not read output — ' + e.message));
        }
      }
    );
  });
}

// Mirrors edge-tts.synthesizeClips' contract so server.js can swap between
// them without special-casing: returns an array of base64 clips. SAPI has no
// practical length limit for our sizes, so this is a single clip.
async function synthesizeClips(text) {
  const buf = await synthesizeToWav(text);
  return [buf.toString('base64')];
}

// Lists installed voices — useful for diagnosing "why does it sound like that".
function listVoices() {
  return new Promise((resolve) => {
    if (!IS_WINDOWS) return resolve([]);
    const ps = `Add-Type -AssemblyName System.Speech; (New-Object System.Speech.Synthesis.SpeechSynthesizer).GetInstalledVoices() | ForEach-Object { $_.VoiceInfo.Name }`;
    execFile('powershell.exe', ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-Command', ps],
      { timeout: 20000, windowsHide: true },
      (err, stdout) => {
        if (err) return resolve([]);
        resolve(String(stdout || '').split(/\r?\n/).map(s => s.trim()).filter(Boolean));
      });
  });
}

module.exports = { synthesizeClips, synthesizeToWav, listVoices, isAvailable, MIME: 'audio/wav' };
